version: "2"

services:
  app:
    image: python:latest
    environment:
      - LANG='en_US.UTF-8'
      - PYTHONDONTWRITEBYTECODE=1
    tty: true
    command: /bin/bash
    working_dir: /root/
    volumes:
      - ./:/root/
    command: bash
    privileged: true
